"""CLI for local, reviewable metadata enrichment."""

import json
from pathlib import Path

import typer

from byzantine.ingestion.pipeline import load_book_config
from byzantine.metadata.enrichment import enrich_chunks

app = typer.Typer(add_completion=False, help="Attach reviewable historical metadata to semantic chunks.")


@app.command()
def run(
    chunks_path: Path = typer.Argument(
        Path("data/processed/oxford_handbook_byzantine_studies/chunks.jsonl"),
        exists=True,
        help="Semantic chunks generated by byzantine-chunk.",
    ),
    seed_path: Path = typer.Option(Path("config/entity_seed.yaml"), help="Reviewed entity/topic seed file."),
    config: Path = typer.Option(Path("config/book.yaml"), help="Project book configuration."),
) -> None:
    """Write enriched_chunks.jsonl and metadata_report.json beside chunks.jsonl."""
    settings = load_book_config(config)
    historical_range = settings.get("metadata", {})
    report = enrich_chunks(
        chunks_path,
        seed_path,
        chunks_path.with_name("enriched_chunks.jsonl"),
        historical_year_min=int(historical_range.get("historical_year_min", 200)),
        historical_year_max=int(historical_range.get("historical_year_max", 1500)),
    )
    chunks_path.with_name("metadata_report.json").write_text(
        json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    typer.echo("; ".join(f"{key}: {value}" for key, value in report.items()))


if __name__ == "__main__":
    app()
