"""CLI for BGE-M3 vector indexing."""

import json
from pathlib import Path

import typer

from byzantine.indexing.vector_index import create_local_index
from byzantine.ingestion.pipeline import load_book_config

app = typer.Typer(
    add_completion=False,
    help="Embed Byzantine chunks with BGE-M3 and persist them in local Qdrant.",
)


@app.command()
def run(
    chunks_path: Path = typer.Argument(
        Path("data/processed/oxford_handbook_byzantine_studies/enriched_chunks.jsonl"),
        exists=True,
        help="Enriched chunks generated by byzantine-enrich.",
    ),
    config: Path = typer.Option(Path("config/book.yaml"), help="Project book configuration."),
    qdrant_path: Path = typer.Option(Path("data/qdrant"), help="Local Qdrant storage directory."),
    recreate: bool = typer.Option(False, help="Delete and rebuild the target collection."),
) -> None:
    """Write dense vectors and complete payloads to local Qdrant."""
    settings = load_book_config(config)
    embedding = settings["embedding"]
    configured_path = Path(str(embedding.get("local_model_path", "")))
    model_name = str(configured_path) if configured_path.is_dir() else str(embedding["model_name"])
    report = create_local_index(
        chunks_path,
        qdrant_path,
        collection_name=str(embedding["collection_name"]),
        model_name=model_name,
        max_length=int(embedding["max_length"]),
        batch_size=int(embedding["batch_size_cpu"]),
        recreate=recreate,
    )
    report_path = chunks_path.with_name("indexing_report.json")
    report_path.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    typer.echo(json.dumps(report, ensure_ascii=False))


if __name__ == "__main__":
    app()
